name: Resume ci Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name2:${{github.run_number}}
    - name: Build latest 
      run: docker build . --file Dockerfile --tag my-image-name2
    - name: login to Docker hub
      run: docker login -u ${{secrets.USER_NAME}} -p ${{secrets.PASSWORD}}
    - name: Tag image 
      run: docker tag my-image-name2:${{github.run_number}} ${{secrets.USER_NAME}}/my-image-name2:${{github.run_number}}


